from libdebug import debugger

d=debugger("test/binaries/basic_test")
d.run()
bp = d.breakpoint(0x4011F4)
bbp= d.breakpoint(0x401296)
d.cont()
#a=d.getMem()
#print(a)
print(hex(d.regs.rip))
d.trace()
d.cont()
d.trace()
print(hex(d.regs.rip))
d.cont()
d.kill()
