#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


    #define INSTRUCTION_POINTER(regs) (regs.rip)
    #define INSTALL_BREAKPOINT(instruction) ((instruction & 0xFFFFFFFFFFFFFF00) | 0xCC)
    #define BREAKPOINT_SIZE 1
    #define IS_SW_BREAKPOINT(instruction) (instruction == 0xCC)
    
    #define IS_RET_INSTRUCTION(instruction) (instruction == 0xC3 || instruction == 0xCB || instruction == 0xC2 || instruction == 0xCA)
    
    // X86_64 Architecture specific
    int IS_CALL_INSTRUCTION(uint8_t* instr)
    {
        // Check for direct CALL (E8 xx xx xx xx)
        if (instr[0] == (uint8_t)0xE8) {
            return 1; // It's a CALL
        }
        
        // Check for indirect CALL using ModR/M (FF /2)
        if (instr[0] == (uint8_t)0xFF) {
            // Extract ModR/M byte
            uint8_t modRM = (uint8_t)instr[1];
            uint8_t reg = (modRM >> 3) & 7; // Middle three bits

            if (reg == 2) {
                return 1; // It's a CALL
            }
        }

        return 0; // Not a CALL
    }
    //
// This file is part of libdebug Python library (https://github.com/libdebug/libdebug).
// Copyright (c) 2023-2024 Roberto Alessandro Bertolini, Gabriele Digregorio, Francesco Panebianco. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
//

#include <errno.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/ptrace.h>
#include <sys/types.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <inttypes.h>

struct ptrace_hit_bp {
    int pid;
    uint64_t addr;
    uint64_t bp_instruction;
    uint64_t prev_instruction;
};

struct software_breakpoint {
    uint64_t addr;
    uint64_t instruction;
    uint64_t patched_instruction;
    char enabled;
    struct software_breakpoint *next;
};

struct thread {
    int tid;
    struct user_regs_struct regs;
    int signal_to_forward;
    struct thread *next;
};

struct thread_status {
    int tid;
    int status;
    struct thread_status *next;
};

struct global_state {
    struct thread *t_HEAD;
    struct software_breakpoint *b_HEAD;
    _Bool handle_syscall_enabled;
};

struct user_regs_struct *register_thread(struct global_state *state, int tid)
{
    // Verify if the thread is already registered
    struct thread *t = state->t_HEAD;
    while (t != NULL) {
        if (t->tid == tid) return &t->regs;
        t = t->next;
    }

    t = malloc(sizeof(struct thread));
    t->tid = tid;
    t->signal_to_forward = 0;

    ptrace(PTRACE_GETREGS, tid, NULL, &t->regs);

    t->next = state->t_HEAD;
    state->t_HEAD = t;

    return &t->regs;
}

void unregister_thread(struct global_state *state, int tid)
{
    struct thread *t = state->t_HEAD;
    struct thread *prev = NULL;

    while (t != NULL) {
        if (t->tid == tid) {
            if (prev == NULL) {
                state->t_HEAD = t->next;
            } else {
                prev->next = t->next;
            }
            free(t);
            return;
        }
        prev = t;
        t = t->next;
    }
}

void free_thread_list(struct global_state *state)
{
    struct thread *t = state->t_HEAD;
    struct thread *next;

    while (t != NULL) {
        next = t->next;
        free(t);
        t = next;
    }

    state->t_HEAD = NULL;
}

int ptrace_trace_me(void)
{
    return ptrace(PTRACE_TRACEME, 0, NULL, NULL);
}

int ptrace_attach(int pid)
{
    return ptrace(PTRACE_ATTACH, pid, NULL, NULL);
}

void ptrace_detach_for_kill(struct global_state *state, int pid)
{
    struct thread *t = state->t_HEAD;
    // note that the order is important: the main thread must be detached last
    while (t != NULL) {
        // let's attempt to read the registers of the thread
        if (ptrace(PTRACE_GETREGS, t->tid, NULL, &t->regs)) {
            // if we can't read the registers, the thread is probably still running
            // ensure that the thread is stopped
            tgkill(pid, t->tid, SIGSTOP);

            // wait for it to stop
            waitpid(t->tid, NULL, 0);
        }

        // detach from it
        if (ptrace(PTRACE_DETACH, t->tid, NULL, NULL))
            fprintf(stderr, "ptrace_detach failed for thread %d: %s\\n", t->tid,
                    strerror(errno));

        // kill it
        tgkill(pid, t->tid, SIGKILL);

        t = t->next;
    }

    waitpid(pid, NULL, 0);
}

void ptrace_detach_for_migration(struct global_state *state, int pid)
{
    struct thread *t = state->t_HEAD;
    // note that the order is important: the main thread must be detached last
    while (t != NULL) {
        // the user might have modified the state of the registers
        // so we use SETREGS to check if the process is running
        if (ptrace(PTRACE_SETREGS, t->tid, NULL, &t->regs)) {
            // if we can't read the registers, the thread is probably still running
            // ensure that the thread is stopped
            tgkill(pid, t->tid, SIGSTOP);

            // wait for it to stop
            waitpid(t->tid, NULL, 0);

            // set the registers again, as the first time it failed
            ptrace(PTRACE_SETREGS, t->tid, NULL, &t->regs);
        }

        // Be sure that the thread will not run during gdb reattachment
        tgkill(pid, t->tid, SIGSTOP);

        // detach from it
        if (ptrace(PTRACE_DETACH, t->tid, NULL, NULL))
            fprintf(stderr, "ptrace_detach failed for thread %d: %s\\n", t->tid,
                    strerror(errno));

        t = t->next;
    }
}

void ptrace_reattach_from_gdb(struct global_state *state, int pid)
{
    struct thread *t = state->t_HEAD;
    // note that the order is important: the main thread must be detached last
    while (t != NULL) {
        if (ptrace(PTRACE_ATTACH, t->tid, NULL, NULL))
            fprintf(stderr, "ptrace_attach failed for thread %d: %s\\n", t->tid,
                    strerror(errno));

        if (ptrace(PTRACE_GETREGS, t->tid, NULL, &t->regs))
            fprintf(stderr, "ptrace_getregs failed for thread %d: %s\\n", t->tid,
                    strerror(errno));

        t = t->next;
    }
}

void ptrace_detach_and_cont(struct global_state *state, int pid)
{
    ptrace_detach_for_migration(state, pid);

    // continue the execution of the process
    kill(pid, SIGCONT);
}

void ptrace_set_options(int pid)
{
    int options = PTRACE_O_TRACEFORK | PTRACE_O_TRACEVFORK | PTRACE_O_TRACESYSGOOD |
                  PTRACE_O_TRACECLONE | PTRACE_O_TRACEEXEC | PTRACE_O_TRACEEXIT;

    ptrace(PTRACE_SETOPTIONS, pid, NULL, options);
}

uint64_t ptrace_peekdata(int pid, uint64_t addr)
{
    // Since the value returned by a successful PTRACE_PEEK*
    // request may be -1, the caller must clear errno before the call,
    errno = 0;

    return ptrace(PTRACE_PEEKDATA, pid, (void *)addr, NULL);
}

uint64_t ptrace_pokedata(int pid, uint64_t addr, uint64_t data)
{
    return ptrace(PTRACE_POKEDATA, pid, (void *)addr, data);
}

uint64_t ptrace_peekuser(int pid, uint64_t addr)
{
    // Since the value returned by a successful PTRACE_PEEK*
    // request may be -1, the caller must clear errno before the call,
    errno = 0;

    return ptrace(PTRACE_PEEKUSER, pid, addr, NULL);
}

uint64_t ptrace_pokeuser(int pid, uint64_t addr, uint64_t data)
{
    return ptrace(PTRACE_POKEUSER, pid, addr, data);
}

uint64_t ptrace_geteventmsg(int pid)
{
    uint64_t data = 0;

    ptrace(PTRACE_GETEVENTMSG, pid, NULL, &data);

    return data;
}

long singlestep(struct global_state *state, int tid)
{
    // flush any register changes
    struct thread *t = state->t_HEAD;
    int signal_to_forward = 0;
    while (t != NULL) {
        if (ptrace(PTRACE_SETREGS, t->tid, NULL, &t->regs))
            perror("ptrace_setregs");
        if (t->tid == tid) {
            signal_to_forward = t->signal_to_forward;
            t->signal_to_forward = 0;
        }
        t = t->next;
    }

    return ptrace(PTRACE_SINGLESTEP, tid, NULL, signal_to_forward);
}

int step_until(struct global_state *state, int tid, uint64_t addr, int max_steps)
{
    // flush any register changes
    struct thread *t = state->t_HEAD, *stepping_thread = NULL;
    while (t != NULL) {
        if (ptrace(PTRACE_SETREGS, t->tid, NULL, &t->regs))
            perror("ptrace_setregs");

        if (t->tid == tid)
            stepping_thread = t;

        t = t->next;
    }

    int count = 0, status = 0;
    uint64_t previous_ip;

    if (!stepping_thread) {
        perror("Thread not found");
        return -1;
    }

    while (max_steps == -1 || count < max_steps) {
        if (ptrace(PTRACE_SINGLESTEP, tid, NULL, NULL)) return -1;

        // wait for the child
        waitpid(tid, &status, 0);

        previous_ip = INSTRUCTION_POINTER(stepping_thread->regs);

        // update the registers
        ptrace(PTRACE_GETREGS, tid, NULL, &stepping_thread->regs);

        if (INSTRUCTION_POINTER(stepping_thread->regs) == addr) break;

        // if the instruction pointer didn't change, we have to step again
        // because we hit a hardware breakpoint
        if (INSTRUCTION_POINTER(stepping_thread->regs) == previous_ip) continue;

        count++;
    }

    return 0;
}

int prepare_for_run(struct global_state *state, int pid)
{
    int status = 0;

    // flush any register changes
    struct thread *t = state->t_HEAD;
    while (t != NULL) {
        if (ptrace(PTRACE_SETREGS, t->tid, NULL, &t->regs))
            fprintf(stderr, "ptrace_setregs failed for thread %d: %s\\n",
                    t->tid, strerror(errno));
        t = t->next;
    }

    // iterate over all the threads and check if any of them has hit a software
    // breakpoint
    t = state->t_HEAD;
    struct software_breakpoint *b;
    int t_hit;

    while (t != NULL) {
        t_hit = 0;
        uint64_t ip = INSTRUCTION_POINTER(t->regs);

        b = state->b_HEAD;
        while (b != NULL && !t_hit) {
            if (b->addr == ip)
                // we hit a software breakpoint on this thread
                t_hit = 1;

            b = b->next;
        }

        if (t_hit) {
            // step over the breakpoint
            if (ptrace(PTRACE_SINGLESTEP, t->tid, NULL, NULL)) return -1;

            // wait for the child
            waitpid(t->tid, &status, 0);

            // status == 4991 ==> (WIFSTOPPED(status) && WSTOPSIG(status) ==
            // SIGSTOP) this should happen only if threads are involved
            if (status == 4991) {
                ptrace(PTRACE_SINGLESTEP, t->tid, NULL, NULL);
                waitpid(t->tid, &status, 0);
            }
        }

        t = t->next;
    }

    // Reset any software breakpoint
    b = state->b_HEAD;
    while (b != NULL) {
        if (b->enabled) {
            ptrace(PTRACE_POKEDATA, pid, (void *)b->addr,
                   b->patched_instruction);
        }
        b = b->next;
    }

    return status;
}

int cont_all_and_set_bps(struct global_state *state, int pid)
{
    int status = prepare_for_run(state, pid);

    // continue the execution of all the threads
    struct thread *t = state->t_HEAD;
    while (t != NULL) {
        if (ptrace(state->handle_syscall_enabled
 ? PTRACE_SYSCALL : PTRACE_CONT, t->tid, NULL, t->signal_to_forward))
            fprintf(stderr, "ptrace_cont failed for thread %d with signal %d: %s\\n", t->tid, t->signal_to_forward,
                    strerror(errno));
        t->signal_to_forward = 0;
        t = t->next;
    }

    return status;
}

struct thread_status *wait_all_and_update_regs(struct global_state *state, int pid)
{
    // Allocate the head of the list
    struct thread_status *head;
    head = malloc(sizeof(struct thread_status));
    head->next = NULL;

    // The first element is the first status we get from polling with waitpid
    head->tid = waitpid(-getpgid(pid), &head->status, 0);

    if (head->tid == -1) {
        free(head);
        perror("waitpid");
        return NULL;
    }

    // We must interrupt all the other threads with a SIGSTOP
    struct thread *t = state->t_HEAD;
    int temp_tid, temp_status;
    while (t != NULL) {
        if (t->tid != head->tid) {
            // If GETREGS succeeds, the thread is already stopped, so we must
            // not "stop" it again
            if (ptrace(PTRACE_GETREGS, t->tid, NULL, &t->regs) == -1) {
                // Stop the thread with a SIGSTOP
                tgkill(pid, t->tid, SIGSTOP);
                // Wait for the thread to stop
                temp_tid = waitpid(t->tid, &temp_status, 0);

                // Register the status of the thread, as it might contain useful
                // information
                struct thread_status *ts = malloc(sizeof(struct thread_status));
                ts->tid = temp_tid;
                ts->status = temp_status;
                ts->next = head;
                head = ts;
            }
        }
        t = t->next;
    }

    // We keep polling but don't block, we want to get all the statuses we can
    while ((temp_tid = waitpid(-getpgid(pid), &temp_status, WNOHANG)) > 0) {
        struct thread_status *ts = malloc(sizeof(struct thread_status));
        ts->tid = temp_tid;
        ts->status = temp_status;
        ts->next = head;
        head = ts;
    }

    // Update the registers of all the threads
    t = state->t_HEAD;
    while (t) {
        ptrace(PTRACE_GETREGS, t->tid, NULL, &t->regs);
        t = t->next;
    }

    // Restore any software breakpoint
    struct software_breakpoint *b = state->b_HEAD;

    while (b != NULL) {
        if (b->enabled) {
            ptrace(PTRACE_POKEDATA, pid, (void *)b->addr, b->instruction);
        }
        b = b->next;
    }

    return head;
}

void free_thread_status_list(struct thread_status *head)
{
    struct thread_status *next;

    while (head) {
        next = head->next;
        free(head);
        head = next;
    }
}

void register_breakpoint(struct global_state *state, int pid, uint64_t address)
{
    uint64_t instruction, patched_instruction;

    instruction = ptrace(PTRACE_PEEKDATA, pid, (void *)address, NULL);

    patched_instruction = INSTALL_BREAKPOINT(instruction);

    ptrace(PTRACE_POKEDATA, pid, (void *)address, patched_instruction);

    struct software_breakpoint *b = state->b_HEAD;

    while (b != NULL) {
        if (b->addr == address) {
            b->enabled = 1;
            return;
        }
        b = b->next;
    }

    b = malloc(sizeof(struct software_breakpoint));
    b->addr = address;
    b->instruction = instruction;
    b->patched_instruction = patched_instruction;
    b->enabled = 1;

    // Breakpoints should be inserted ordered by address, increasing
    // This is important, because we don't want a breakpoint patching another
    if (state->b_HEAD == NULL || state->b_HEAD->addr > address) {
        b->next = state->b_HEAD;
        state->b_HEAD = b;
        return;
    } else {
        struct software_breakpoint *prev = state->b_HEAD;
        struct software_breakpoint *next = state->b_HEAD->next;

        while (next != NULL && next->addr < address) {
            prev = next;
            next = next->next;
        }

        b->next = next;
        prev->next = b;
    }
}

void unregister_breakpoint(struct global_state *state, uint64_t address)
{
    struct software_breakpoint *b = state->b_HEAD;
    struct software_breakpoint *prev = NULL;

    while (b != NULL) {
        if (b->addr == address) {
            if (prev == NULL) {
                state->b_HEAD = b->next;
            } else {
                prev->next = b->next;
            }
            free(b);
            return;
        }
        prev = b;
        b = b->next;
    }
}

void enable_breakpoint(struct global_state *state, uint64_t address)
{
    struct software_breakpoint *b = state->b_HEAD;

    while (b != NULL) {
        if (b->addr == address) {
            b->enabled = 1;
        }
        b = b->next;
    }
}

void disable_breakpoint(struct global_state *state, uint64_t address)
{
    struct software_breakpoint *b = state->b_HEAD;

    while (b != NULL) {
        if (b->addr == address) {
            b->enabled = 0;
        }
        b = b->next;
    }
}

void free_breakpoints(struct global_state *state)
{
    struct software_breakpoint *b = state->b_HEAD;
    struct software_breakpoint *next;

    while (b != NULL) {
        next = b->next;
        free(b);
        b = next;
    }

    state->b_HEAD = NULL;
}

int stepping_cont(struct global_state *state, int tid, uint64_t map_start, uint64_t map_end)
{
    //prepare_for_run(state, tid);

    struct thread *stepping_thread = state->t_HEAD;
    while (stepping_thread != NULL) {
        if (stepping_thread->tid == tid) {
            break;
        }

        stepping_thread = stepping_thread->next;
    }

    if (!stepping_thread) {
        perror("Thread not found");
        return -1;
    }

    uint64_t previous_ip, current_ip;
    uint64_t first_opcode_byte, opcode_window;
    int count=0, status=0;

    do{
        if (ptrace(PTRACE_SINGLESTEP, tid, NULL, NULL)) return -1;

        waitpid(tid, &status, 0);

        previous_ip = INSTRUCTION_POINTER(stepping_thread->regs);

        // update the registers
        ptrace(PTRACE_GETREGS, tid, NULL, &stepping_thread->regs);

        current_ip = INSTRUCTION_POINTER(stepping_thread->regs);

        // Get value at current instruction pointer
        opcode_window = ptrace(PTRACE_PEEKDATA, tid, (void *)current_ip, NULL);
        first_opcode_byte = opcode_window & 0xFF;

        if(current_ip < map_end && current_ip > map_start){
            printf("%" PRIu64 "  ", previous_ip);
            printf("%" PRIu64 "\n", current_ip);
        }

        // if the instruction pointer didn't change, we return
        // because we hit a hardware breakpoint
        // we do the same if we hit a software breakpoint
        if (current_ip == previous_ip || IS_SW_BREAKPOINT(first_opcode_byte))
            break;

        // We have not hit a breakpoint, hence the counter increased
        //we only increase in case we are inside the mapped code region if external is on (marked by ap_end and map_start being identical)
        if((map_end != map_start) && current_ip < map_end && current_ip > map_start){
            count++;
        }
    } while(count<20);

    return count;
}

int stepping_finish(struct global_state *state, int tid)
{
    int status = prepare_for_run(state, tid);

    struct thread *stepping_thread = state->t_HEAD;
    while (stepping_thread != NULL) {
        if (stepping_thread->tid == tid) {
            break;
        }

        stepping_thread = stepping_thread->next;
    }

    if (!stepping_thread) {
        perror("Thread not found");
        return -1;
    }

    uint64_t previous_ip, current_ip;
    uint64_t opcode_window, first_opcode_byte;

    // We need to keep track of the nested calls
    int nested_call_counter = 1;

    do {
        if (ptrace(PTRACE_SINGLESTEP, tid, NULL, NULL)) return -1;

        // wait for the child
        waitpid(tid, &status, 0);

        previous_ip = INSTRUCTION_POINTER(stepping_thread->regs);

        // update the registers
        ptrace(PTRACE_GETREGS, tid, NULL, &stepping_thread->regs);

        current_ip = INSTRUCTION_POINTER(stepping_thread->regs);

        // Get value at current instruction pointer
        opcode_window = ptrace(PTRACE_PEEKDATA, tid, (void *)current_ip, NULL);
        first_opcode_byte = opcode_window & 0xFF;

        // if the instruction pointer didn't change, we return
        // because we hit a hardware breakpoint
        // we do the same if we hit a software breakpoint
        if (current_ip == previous_ip || IS_SW_BREAKPOINT(first_opcode_byte))
            goto cleanup;
        
        // If we hit a call instruction, we increment the counter
        if (IS_CALL_INSTRUCTION((uint8_t*) &opcode_window))
            nested_call_counter++;
        else if (IS_RET_INSTRUCTION(first_opcode_byte))
            nested_call_counter--;

    } while (nested_call_counter > 0);

    // We are in a return instruction, do the last step
    if (ptrace(PTRACE_SINGLESTEP, tid, NULL, NULL)) return -1;

    // wait for the child
    waitpid(tid, &status, 0);

    // update the registers
    ptrace(PTRACE_GETREGS, tid, NULL, &stepping_thread->regs);

cleanup:
    // remove any installed breakpoint
    struct software_breakpoint *b = state->b_HEAD;
    while (b != NULL) {
        if (b->enabled) {
            ptrace(PTRACE_POKEDATA, tid, (void *)b->addr, b->instruction);
        }
        b = b->next;
    }

    return status;
}


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // int()(int)
/*  1 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // int()(struct global_state *, int)
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 70), // struct global_state *
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // int()(struct global_state *, int, uint64_t, int)
/*  8 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/*  9 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 10 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // int()(struct global_state *, int, uint64_t, uint64_t)
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 15 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 16 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 17 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // int()(void)
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 69), // long()(struct global_state *, int)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 24 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION, 65), // struct thread_status *()(struct global_state *, int)
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 27 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION, 77), // struct user_regs_struct *()(struct global_state *, int)
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION, 10), // uint64_t()(int)
/* 34 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION, 10), // uint64_t()(int, uint64_t)
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION, 10), // uint64_t()(int, uint64_t, uint64_t)
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 44 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION, 80), // void()(int)
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 80), // void()(struct global_state *)
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 50 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 51 */ _CFFI_OP(_CFFI_OP_FUNCTION, 80), // void()(struct global_state *, int)
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 53 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 54 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION, 80), // void()(struct global_state *, int, uint64_t)
/* 56 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 57 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 58 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 59 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 60 */ _CFFI_OP(_CFFI_OP_FUNCTION, 80), // void()(struct global_state *, uint64_t)
/* 61 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 63 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 64 */ _CFFI_OP(_CFFI_OP_FUNCTION, 80), // void()(struct thread_status *)
/* 65 */ _CFFI_OP(_CFFI_OP_POINTER, 76), // struct thread_status *
/* 66 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 67 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 68 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 69 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 9), // long
/* 70 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // struct global_state
/* 71 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct ptrace_hit_bp
/* 72 */ _CFFI_OP(_CFFI_OP_POINTER, 73), // struct software_breakpoint *
/* 73 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // struct software_breakpoint
/* 74 */ _CFFI_OP(_CFFI_OP_POINTER, 75), // struct thread *
/* 75 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // struct thread
/* 76 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // struct thread_status
/* 77 */ _CFFI_OP(_CFFI_OP_POINTER, 78), // struct user_regs_struct *
/* 78 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // struct user_regs_struct
/* 79 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 10), // unsigned long
/* 80 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_d_cont_all_and_set_bps(struct global_state * x0, int x1)
{
  return cont_all_and_set_bps(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_cont_all_and_set_bps(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "cont_all_and_set_bps", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = cont_all_and_set_bps(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_cont_all_and_set_bps _cffi_d_cont_all_and_set_bps
#endif

static void _cffi_d_disable_breakpoint(struct global_state * x0, uint64_t x1)
{
  disable_breakpoint(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_disable_breakpoint(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  uint64_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "disable_breakpoint", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { disable_breakpoint(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_disable_breakpoint _cffi_d_disable_breakpoint
#endif

static void _cffi_d_enable_breakpoint(struct global_state * x0, uint64_t x1)
{
  enable_breakpoint(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_enable_breakpoint(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  uint64_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "enable_breakpoint", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { enable_breakpoint(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_enable_breakpoint _cffi_d_enable_breakpoint
#endif

static void _cffi_d_free_breakpoints(struct global_state * x0)
{
  free_breakpoints(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_breakpoints(PyObject *self, PyObject *arg0)
{
  struct global_state * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { free_breakpoints(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_free_breakpoints _cffi_d_free_breakpoints
#endif

static void _cffi_d_free_thread_list(struct global_state * x0)
{
  free_thread_list(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_thread_list(PyObject *self, PyObject *arg0)
{
  struct global_state * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { free_thread_list(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_free_thread_list _cffi_d_free_thread_list
#endif

static void _cffi_d_free_thread_status_list(struct thread_status * x0)
{
  free_thread_status_list(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_thread_status_list(PyObject *self, PyObject *arg0)
{
  struct thread_status * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(65), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct thread_status *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(65), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { free_thread_status_list(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_free_thread_status_list _cffi_d_free_thread_status_list
#endif

static int _cffi_d_ptrace_attach(int x0)
{
  return ptrace_attach(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_attach(PyObject *self, PyObject *arg0)
{
  int x0;
  int result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_attach(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_attach _cffi_d_ptrace_attach
#endif

static void _cffi_d_ptrace_detach_and_cont(struct global_state * x0, int x1)
{
  ptrace_detach_and_cont(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_detach_and_cont(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ptrace_detach_and_cont", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ptrace_detach_and_cont(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ptrace_detach_and_cont _cffi_d_ptrace_detach_and_cont
#endif

static void _cffi_d_ptrace_detach_for_kill(struct global_state * x0, int x1)
{
  ptrace_detach_for_kill(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_detach_for_kill(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ptrace_detach_for_kill", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ptrace_detach_for_kill(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ptrace_detach_for_kill _cffi_d_ptrace_detach_for_kill
#endif

static void _cffi_d_ptrace_detach_for_migration(struct global_state * x0, int x1)
{
  ptrace_detach_for_migration(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_detach_for_migration(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ptrace_detach_for_migration", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ptrace_detach_for_migration(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ptrace_detach_for_migration _cffi_d_ptrace_detach_for_migration
#endif

static uint64_t _cffi_d_ptrace_geteventmsg(int x0)
{
  return ptrace_geteventmsg(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_geteventmsg(PyObject *self, PyObject *arg0)
{
  int x0;
  uint64_t result;
  PyObject *pyresult;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_geteventmsg(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, uint64_t);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_geteventmsg _cffi_d_ptrace_geteventmsg
#endif

static uint64_t _cffi_d_ptrace_peekdata(int x0, uint64_t x1)
{
  return ptrace_peekdata(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_peekdata(PyObject *self, PyObject *args)
{
  int x0;
  uint64_t x1;
  uint64_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ptrace_peekdata", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_peekdata(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, uint64_t);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_peekdata _cffi_d_ptrace_peekdata
#endif

static uint64_t _cffi_d_ptrace_peekuser(int x0, uint64_t x1)
{
  return ptrace_peekuser(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_peekuser(PyObject *self, PyObject *args)
{
  int x0;
  uint64_t x1;
  uint64_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ptrace_peekuser", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_peekuser(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, uint64_t);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_peekuser _cffi_d_ptrace_peekuser
#endif

static uint64_t _cffi_d_ptrace_pokedata(int x0, uint64_t x1, uint64_t x2)
{
  return ptrace_pokedata(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_pokedata(PyObject *self, PyObject *args)
{
  int x0;
  uint64_t x1;
  uint64_t x2;
  uint64_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ptrace_pokedata", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint64_t);
  if (x2 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_pokedata(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, uint64_t);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_pokedata _cffi_d_ptrace_pokedata
#endif

static uint64_t _cffi_d_ptrace_pokeuser(int x0, uint64_t x1, uint64_t x2)
{
  return ptrace_pokeuser(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_pokeuser(PyObject *self, PyObject *args)
{
  int x0;
  uint64_t x1;
  uint64_t x2;
  uint64_t result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "ptrace_pokeuser", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint64_t);
  if (x2 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_pokeuser(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, uint64_t);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_pokeuser _cffi_d_ptrace_pokeuser
#endif

static void _cffi_d_ptrace_reattach_from_gdb(struct global_state * x0, int x1)
{
  ptrace_reattach_from_gdb(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_reattach_from_gdb(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ptrace_reattach_from_gdb", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ptrace_reattach_from_gdb(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ptrace_reattach_from_gdb _cffi_d_ptrace_reattach_from_gdb
#endif

static void _cffi_d_ptrace_set_options(int x0)
{
  ptrace_set_options(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_set_options(PyObject *self, PyObject *arg0)
{
  int x0;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { ptrace_set_options(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_ptrace_set_options _cffi_d_ptrace_set_options
#endif

static int _cffi_d_ptrace_trace_me(void)
{
  return ptrace_trace_me();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ptrace_trace_me(PyObject *self, PyObject *noarg)
{
  int result;
  PyObject *pyresult;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ptrace_trace_me(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  return pyresult;
}
#else
#  define _cffi_f_ptrace_trace_me _cffi_d_ptrace_trace_me
#endif

static void _cffi_d_register_breakpoint(struct global_state * x0, int x1, uint64_t x2)
{
  register_breakpoint(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_register_breakpoint(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  uint64_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "register_breakpoint", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint64_t);
  if (x2 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { register_breakpoint(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_register_breakpoint _cffi_d_register_breakpoint
#endif

static struct user_regs_struct * _cffi_d_register_thread(struct global_state * x0, int x1)
{
  return register_thread(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_register_thread(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct user_regs_struct * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "register_thread", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = register_thread(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(77));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_register_thread _cffi_d_register_thread
#endif

static long _cffi_d_singlestep(struct global_state * x0, int x1)
{
  return singlestep(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_singlestep(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  long result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "singlestep", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = singlestep(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, long);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_singlestep _cffi_d_singlestep
#endif

static int _cffi_d_step_until(struct global_state * x0, int x1, uint64_t x2, int x3)
{
  return step_until(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_step_until(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  uint64_t x2;
  int x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "step_until", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint64_t);
  if (x2 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, int);
  if (x3 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = step_until(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_step_until _cffi_d_step_until
#endif

static int _cffi_d_stepping_cont(struct global_state * x0, int x1, uint64_t x2, uint64_t x3)
{
  return stepping_cont(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_stepping_cont(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  uint64_t x2;
  uint64_t x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "stepping_cont", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint64_t);
  if (x2 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, uint64_t);
  if (x3 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = stepping_cont(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_stepping_cont _cffi_d_stepping_cont
#endif

static int _cffi_d_stepping_finish(struct global_state * x0, int x1)
{
  return stepping_finish(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_stepping_finish(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "stepping_finish", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = stepping_finish(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_stepping_finish _cffi_d_stepping_finish
#endif

static void _cffi_d_unregister_breakpoint(struct global_state * x0, uint64_t x1)
{
  unregister_breakpoint(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_unregister_breakpoint(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  uint64_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "unregister_breakpoint", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint64_t);
  if (x1 == (uint64_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { unregister_breakpoint(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_unregister_breakpoint _cffi_d_unregister_breakpoint
#endif

static void _cffi_d_unregister_thread(struct global_state * x0, int x1)
{
  unregister_thread(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_unregister_thread(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "unregister_thread", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { unregister_thread(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_unregister_thread _cffi_d_unregister_thread
#endif

static struct thread_status * _cffi_d_wait_all_and_update_regs(struct global_state * x0, int x1)
{
  return wait_all_and_update_regs(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_wait_all_and_update_regs(PyObject *self, PyObject *args)
{
  struct global_state * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  struct thread_status * result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "wait_all_and_update_regs", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct global_state *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = wait_all_and_update_regs(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(65));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_wait_all_and_update_regs _cffi_d_wait_all_and_update_regs
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_global_state(struct global_state *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { struct thread * *tmp = &p->t_HEAD; (void)tmp; }
  { struct software_breakpoint * *tmp = &p->b_HEAD; (void)tmp; }
  (void)((p->handle_syscall_enabled) | 0);  /* check that 'struct global_state.handle_syscall_enabled' is an integer */
}
struct _cffi_align_struct_global_state { char x; struct global_state y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_ptrace_hit_bp(struct ptrace_hit_bp *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->pid) | 0);  /* check that 'struct ptrace_hit_bp.pid' is an integer */
  (void)((p->addr) | 0);  /* check that 'struct ptrace_hit_bp.addr' is an integer */
  (void)((p->bp_instruction) | 0);  /* check that 'struct ptrace_hit_bp.bp_instruction' is an integer */
  (void)((p->prev_instruction) | 0);  /* check that 'struct ptrace_hit_bp.prev_instruction' is an integer */
}
struct _cffi_align_struct_ptrace_hit_bp { char x; struct ptrace_hit_bp y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_software_breakpoint(struct software_breakpoint *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->addr) | 0);  /* check that 'struct software_breakpoint.addr' is an integer */
  (void)((p->instruction) | 0);  /* check that 'struct software_breakpoint.instruction' is an integer */
  (void)((p->patched_instruction) | 0);  /* check that 'struct software_breakpoint.patched_instruction' is an integer */
  { char *tmp = &p->enabled; (void)tmp; }
  { struct software_breakpoint * *tmp = &p->next; (void)tmp; }
}
struct _cffi_align_struct_software_breakpoint { char x; struct software_breakpoint y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_thread(struct thread *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->tid) | 0);  /* check that 'struct thread.tid' is an integer */
  { struct user_regs_struct *tmp = &p->regs; (void)tmp; }
  (void)((p->signal_to_forward) | 0);  /* check that 'struct thread.signal_to_forward' is an integer */
  { struct thread * *tmp = &p->next; (void)tmp; }
}
struct _cffi_align_struct_thread { char x; struct thread y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_thread_status(struct thread_status *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->tid) | 0);  /* check that 'struct thread_status.tid' is an integer */
  (void)((p->status) | 0);  /* check that 'struct thread_status.status' is an integer */
  { struct thread_status * *tmp = &p->next; (void)tmp; }
}
struct _cffi_align_struct_thread_status { char x; struct thread_status y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_user_regs_struct(struct user_regs_struct *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->r15) | 0);  /* check that 'struct user_regs_struct.r15' is an integer */
  (void)((p->r14) | 0);  /* check that 'struct user_regs_struct.r14' is an integer */
  (void)((p->r13) | 0);  /* check that 'struct user_regs_struct.r13' is an integer */
  (void)((p->r12) | 0);  /* check that 'struct user_regs_struct.r12' is an integer */
  (void)((p->rbp) | 0);  /* check that 'struct user_regs_struct.rbp' is an integer */
  (void)((p->rbx) | 0);  /* check that 'struct user_regs_struct.rbx' is an integer */
  (void)((p->r11) | 0);  /* check that 'struct user_regs_struct.r11' is an integer */
  (void)((p->r10) | 0);  /* check that 'struct user_regs_struct.r10' is an integer */
  (void)((p->r9) | 0);  /* check that 'struct user_regs_struct.r9' is an integer */
  (void)((p->r8) | 0);  /* check that 'struct user_regs_struct.r8' is an integer */
  (void)((p->rax) | 0);  /* check that 'struct user_regs_struct.rax' is an integer */
  (void)((p->rcx) | 0);  /* check that 'struct user_regs_struct.rcx' is an integer */
  (void)((p->rdx) | 0);  /* check that 'struct user_regs_struct.rdx' is an integer */
  (void)((p->rsi) | 0);  /* check that 'struct user_regs_struct.rsi' is an integer */
  (void)((p->rdi) | 0);  /* check that 'struct user_regs_struct.rdi' is an integer */
  (void)((p->orig_rax) | 0);  /* check that 'struct user_regs_struct.orig_rax' is an integer */
  (void)((p->rip) | 0);  /* check that 'struct user_regs_struct.rip' is an integer */
  (void)((p->cs) | 0);  /* check that 'struct user_regs_struct.cs' is an integer */
  (void)((p->eflags) | 0);  /* check that 'struct user_regs_struct.eflags' is an integer */
  (void)((p->rsp) | 0);  /* check that 'struct user_regs_struct.rsp' is an integer */
  (void)((p->ss) | 0);  /* check that 'struct user_regs_struct.ss' is an integer */
  (void)((p->fs_base) | 0);  /* check that 'struct user_regs_struct.fs_base' is an integer */
  (void)((p->gs_base) | 0);  /* check that 'struct user_regs_struct.gs_base' is an integer */
  (void)((p->ds) | 0);  /* check that 'struct user_regs_struct.ds' is an integer */
  (void)((p->es) | 0);  /* check that 'struct user_regs_struct.es' is an integer */
  (void)((p->fs) | 0);  /* check that 'struct user_regs_struct.fs' is an integer */
  (void)((p->gs) | 0);  /* check that 'struct user_regs_struct.gs' is an integer */
}
struct _cffi_align_struct_user_regs_struct { char x; struct user_regs_struct y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "cont_all_and_set_bps", (void *)_cffi_f_cont_all_and_set_bps, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d_cont_all_and_set_bps },
  { "disable_breakpoint", (void *)_cffi_f_disable_breakpoint, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 60), (void *)_cffi_d_disable_breakpoint },
  { "enable_breakpoint", (void *)_cffi_f_enable_breakpoint, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 60), (void *)_cffi_d_enable_breakpoint },
  { "free_breakpoints", (void *)_cffi_f_free_breakpoints, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 48), (void *)_cffi_d_free_breakpoints },
  { "free_thread_list", (void *)_cffi_f_free_thread_list, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 48), (void *)_cffi_d_free_thread_list },
  { "free_thread_status_list", (void *)_cffi_f_free_thread_status_list, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 64), (void *)_cffi_d_free_thread_status_list },
  { "ptrace_attach", (void *)_cffi_f_ptrace_attach, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_ptrace_attach },
  { "ptrace_detach_and_cont", (void *)_cffi_f_ptrace_detach_and_cont, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 51), (void *)_cffi_d_ptrace_detach_and_cont },
  { "ptrace_detach_for_kill", (void *)_cffi_f_ptrace_detach_for_kill, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 51), (void *)_cffi_d_ptrace_detach_for_kill },
  { "ptrace_detach_for_migration", (void *)_cffi_f_ptrace_detach_for_migration, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 51), (void *)_cffi_d_ptrace_detach_for_migration },
  { "ptrace_geteventmsg", (void *)_cffi_f_ptrace_geteventmsg, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 33), (void *)_cffi_d_ptrace_geteventmsg },
  { "ptrace_peekdata", (void *)_cffi_f_ptrace_peekdata, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 36), (void *)_cffi_d_ptrace_peekdata },
  { "ptrace_peekuser", (void *)_cffi_f_ptrace_peekuser, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 36), (void *)_cffi_d_ptrace_peekuser },
  { "ptrace_pokedata", (void *)_cffi_f_ptrace_pokedata, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 40), (void *)_cffi_d_ptrace_pokedata },
  { "ptrace_pokeuser", (void *)_cffi_f_ptrace_pokeuser, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 40), (void *)_cffi_d_ptrace_pokeuser },
  { "ptrace_reattach_from_gdb", (void *)_cffi_f_ptrace_reattach_from_gdb, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 51), (void *)_cffi_d_ptrace_reattach_from_gdb },
  { "ptrace_set_options", (void *)_cffi_f_ptrace_set_options, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 45), (void *)_cffi_d_ptrace_set_options },
  { "ptrace_trace_me", (void *)_cffi_f_ptrace_trace_me, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 19), (void *)_cffi_d_ptrace_trace_me },
  { "register_breakpoint", (void *)_cffi_f_register_breakpoint, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 55), (void *)_cffi_d_register_breakpoint },
  { "register_thread", (void *)_cffi_f_register_thread, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_register_thread },
  { "singlestep", (void *)_cffi_f_singlestep, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d_singlestep },
  { "step_until", (void *)_cffi_f_step_until, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 7), (void *)_cffi_d_step_until },
  { "stepping_cont", (void *)_cffi_f_stepping_cont, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 13), (void *)_cffi_d_stepping_cont },
  { "stepping_finish", (void *)_cffi_f_stepping_finish, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d_stepping_finish },
  { "unregister_breakpoint", (void *)_cffi_f_unregister_breakpoint, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 60), (void *)_cffi_d_unregister_breakpoint },
  { "unregister_thread", (void *)_cffi_f_unregister_thread, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 51), (void *)_cffi_d_unregister_thread },
  { "wait_all_and_update_regs", (void *)_cffi_f_wait_all_and_update_regs, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 25), (void *)_cffi_d_wait_all_and_update_regs },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "t_HEAD", offsetof(struct global_state, t_HEAD),
              sizeof(((struct global_state *)0)->t_HEAD),
              _CFFI_OP(_CFFI_OP_NOOP, 74) },
  { "b_HEAD", offsetof(struct global_state, b_HEAD),
              sizeof(((struct global_state *)0)->b_HEAD),
              _CFFI_OP(_CFFI_OP_NOOP, 72) },
  { "handle_syscall_enabled", offsetof(struct global_state, handle_syscall_enabled),
                              sizeof(((struct global_state *)0)->handle_syscall_enabled),
                              _CFFI_OP(_CFFI_OP_NOOP, 67) },
  { "pid", offsetof(struct ptrace_hit_bp, pid),
           sizeof(((struct ptrace_hit_bp *)0)->pid),
           _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "addr", offsetof(struct ptrace_hit_bp, addr),
            sizeof(((struct ptrace_hit_bp *)0)->addr),
            _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "bp_instruction", offsetof(struct ptrace_hit_bp, bp_instruction),
                      sizeof(((struct ptrace_hit_bp *)0)->bp_instruction),
                      _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "prev_instruction", offsetof(struct ptrace_hit_bp, prev_instruction),
                        sizeof(((struct ptrace_hit_bp *)0)->prev_instruction),
                        _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "addr", offsetof(struct software_breakpoint, addr),
            sizeof(((struct software_breakpoint *)0)->addr),
            _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "instruction", offsetof(struct software_breakpoint, instruction),
                   sizeof(((struct software_breakpoint *)0)->instruction),
                   _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "patched_instruction", offsetof(struct software_breakpoint, patched_instruction),
                           sizeof(((struct software_breakpoint *)0)->patched_instruction),
                           _CFFI_OP(_CFFI_OP_NOOP, 10) },
  { "enabled", offsetof(struct software_breakpoint, enabled),
               sizeof(((struct software_breakpoint *)0)->enabled),
               _CFFI_OP(_CFFI_OP_NOOP, 68) },
  { "next", offsetof(struct software_breakpoint, next),
            sizeof(((struct software_breakpoint *)0)->next),
            _CFFI_OP(_CFFI_OP_NOOP, 72) },
  { "tid", offsetof(struct thread, tid),
           sizeof(((struct thread *)0)->tid),
           _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "regs", offsetof(struct thread, regs),
            sizeof(((struct thread *)0)->regs),
            _CFFI_OP(_CFFI_OP_NOOP, 78) },
  { "signal_to_forward", offsetof(struct thread, signal_to_forward),
                         sizeof(((struct thread *)0)->signal_to_forward),
                         _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "next", offsetof(struct thread, next),
            sizeof(((struct thread *)0)->next),
            _CFFI_OP(_CFFI_OP_NOOP, 74) },
  { "tid", offsetof(struct thread_status, tid),
           sizeof(((struct thread_status *)0)->tid),
           _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "status", offsetof(struct thread_status, status),
              sizeof(((struct thread_status *)0)->status),
              _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "next", offsetof(struct thread_status, next),
            sizeof(((struct thread_status *)0)->next),
            _CFFI_OP(_CFFI_OP_NOOP, 65) },
  { "r15", offsetof(struct user_regs_struct, r15),
           sizeof(((struct user_regs_struct *)0)->r15),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r14", offsetof(struct user_regs_struct, r14),
           sizeof(((struct user_regs_struct *)0)->r14),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r13", offsetof(struct user_regs_struct, r13),
           sizeof(((struct user_regs_struct *)0)->r13),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r12", offsetof(struct user_regs_struct, r12),
           sizeof(((struct user_regs_struct *)0)->r12),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rbp", offsetof(struct user_regs_struct, rbp),
           sizeof(((struct user_regs_struct *)0)->rbp),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rbx", offsetof(struct user_regs_struct, rbx),
           sizeof(((struct user_regs_struct *)0)->rbx),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r11", offsetof(struct user_regs_struct, r11),
           sizeof(((struct user_regs_struct *)0)->r11),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r10", offsetof(struct user_regs_struct, r10),
           sizeof(((struct user_regs_struct *)0)->r10),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r9", offsetof(struct user_regs_struct, r9),
          sizeof(((struct user_regs_struct *)0)->r9),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "r8", offsetof(struct user_regs_struct, r8),
          sizeof(((struct user_regs_struct *)0)->r8),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rax", offsetof(struct user_regs_struct, rax),
           sizeof(((struct user_regs_struct *)0)->rax),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rcx", offsetof(struct user_regs_struct, rcx),
           sizeof(((struct user_regs_struct *)0)->rcx),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rdx", offsetof(struct user_regs_struct, rdx),
           sizeof(((struct user_regs_struct *)0)->rdx),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rsi", offsetof(struct user_regs_struct, rsi),
           sizeof(((struct user_regs_struct *)0)->rsi),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rdi", offsetof(struct user_regs_struct, rdi),
           sizeof(((struct user_regs_struct *)0)->rdi),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "orig_rax", offsetof(struct user_regs_struct, orig_rax),
                sizeof(((struct user_regs_struct *)0)->orig_rax),
                _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rip", offsetof(struct user_regs_struct, rip),
           sizeof(((struct user_regs_struct *)0)->rip),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "cs", offsetof(struct user_regs_struct, cs),
          sizeof(((struct user_regs_struct *)0)->cs),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "eflags", offsetof(struct user_regs_struct, eflags),
              sizeof(((struct user_regs_struct *)0)->eflags),
              _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "rsp", offsetof(struct user_regs_struct, rsp),
           sizeof(((struct user_regs_struct *)0)->rsp),
           _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "ss", offsetof(struct user_regs_struct, ss),
          sizeof(((struct user_regs_struct *)0)->ss),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "fs_base", offsetof(struct user_regs_struct, fs_base),
               sizeof(((struct user_regs_struct *)0)->fs_base),
               _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "gs_base", offsetof(struct user_regs_struct, gs_base),
               sizeof(((struct user_regs_struct *)0)->gs_base),
               _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "ds", offsetof(struct user_regs_struct, ds),
          sizeof(((struct user_regs_struct *)0)->ds),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "es", offsetof(struct user_regs_struct, es),
          sizeof(((struct user_regs_struct *)0)->es),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "fs", offsetof(struct user_regs_struct, fs),
          sizeof(((struct user_regs_struct *)0)->fs),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "gs", offsetof(struct user_regs_struct, gs),
          sizeof(((struct user_regs_struct *)0)->gs),
          _CFFI_OP(_CFFI_OP_NOOP, 79) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "global_state", 70, _CFFI_F_CHECK_FIELDS,
    sizeof(struct global_state), offsetof(struct _cffi_align_struct_global_state, y), 0, 3 },
  { "ptrace_hit_bp", 71, _CFFI_F_CHECK_FIELDS,
    sizeof(struct ptrace_hit_bp), offsetof(struct _cffi_align_struct_ptrace_hit_bp, y), 3, 4 },
  { "software_breakpoint", 73, _CFFI_F_CHECK_FIELDS,
    sizeof(struct software_breakpoint), offsetof(struct _cffi_align_struct_software_breakpoint, y), 7, 5 },
  { "thread", 75, _CFFI_F_CHECK_FIELDS,
    sizeof(struct thread), offsetof(struct _cffi_align_struct_thread, y), 12, 4 },
  { "thread_status", 76, _CFFI_F_CHECK_FIELDS,
    sizeof(struct thread_status), offsetof(struct _cffi_align_struct_thread_status, y), 16, 3 },
  { "user_regs_struct", 78, _CFFI_F_CHECK_FIELDS,
    sizeof(struct user_regs_struct), offsetof(struct _cffi_align_struct_user_regs_struct, y), 19, 27 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  NULL,  /* no typenames */
  27,  /* num_globals */
  6,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  81,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__ptrace_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__ptrace_cffi(void) { return NULL; }
#  else
     init_ptrace_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__ptrace_cffi(void)
{
  return _cffi_init("libdebug.cffi._ptrace_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_ptrace_cffi(void)
{
  _cffi_init("libdebug.cffi._ptrace_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
